var SGE=SGE||{};SGE.Param=SGE.Param||{};SGE.Const=SGE.Const||{};SGE.Var=SGE.Var||{};SGE.mydata=SGE.mydata||{};SGE.Inst=SGE.Inst||{};SGE.Class=SGE.Class||{};SGE.Event=$({});SGE.Const.SKININTRO="intro";SGE.Const.SKINSTUDY="study";SGE.Const.SKINREAD="read";SGE.Const.SKINSTRONG="strong";SGE.Const.SKINREALIZE="realize";SGE.Const.SKINTEST="test";
(function(a){var b=location.href.split("?");if(1<b.length)for(var b=b[1].split("&"),d=0;d<b.length;d++){var f=b[d].split("="),e=f[0];try{var c=f[1]}catch(g){c=""}"plan_de"==e?a.Param.planDe=c:"module_no"==e?a.Param.moduleNo=c:"subj_lesson_no"==e?a.Param.subjLessonNo=c:"subj_no"==e?a.Param.subjNo=c:"student_no"==e?a.Param.studentNo=c:"dictionary_no"==e?a.Param.dictionaryNo=c:"f_test_id"==e?a.Param.fTestId=c:"studying"==e?a.Param.studying=c:"adminmode"==e?a.Param.adminmode=c:"movieLimit"==e&&(a.Param.movieLimit=
c)}a.Param.subjLessonNo="7280";a.Param.subjNo="257";a.Param.planDe="";a.Param.moduleNo="";a.Param.studentNo="";a.Const.xmlName="xml/jr_kuk_601_03.xml";a.Const.studying=a.Param.studying;a.Const.adminmode=a.Param.adminmode;a.Const.testMode="N";a.Const.plan_de=a.Param.planDe;a.Const.module_no=a.Param.moduleNo;a.Const.student_no=a.Param.studentNo;a.Const.movieLimit=a.Param.movieLimit})(SGE);SGE=SGE||{};SGE.Event=SGE.Event||$({});SGE.Event.Const=SGE.Event.Const||{};SGE.Event.Const.StartLoadSkin="startLoadSkin";SGE.Event.on(SGE.Event.Const.StartLoadSkin,{},function(a,b){SGE.loadSkin(b,"#"+b+"-skin","#skin")});SGE=SGE||{};SGE.Class=SGE.Class||{};SGE.getSkinClassInstance=function(a){var b;switch(a){case "intro":b=new SGE.Class.IntroSkinClass}return b};SGE.Class.IntroSkinClass=function(){};SGE.Class.IntroSkinClass.prototype={setStage:function(a){trace("IntroSkinFunc > setStage");$("#unit").html("<h2>"+SGE.mydata.unit+"</h2>");$("#enter").click(function(){SGE.Event.trigger(SGE.Event.Const.StartLoadSkin,SGE.Const.SKINSTUDY)})}};$(document).ready(function(){SGE.setSpinner();$.ajax({type:"GET",url:SGE.Const.xmlName,dataType:"xml",success:SGE.parseMetaXml,error:function(a,b,d){console.log(b,d)}})});function trace(a){try{console.log.apply(console,arguments)}catch(b){}}
SGE.setSpinner=function(){var a=document.getElementById("spinner");(new Spinner({lines:13,length:20,width:10,radius:30,corners:1,rotate:0,direction:1,color:"#000",speed:1,trail:60,shadow:!1,hwaccel:!1,className:"spinner",zIndex:2E9,top:"50%",left:"50%"})).spin(a);SGE.Inst.spinner=$("#spinner").hide();$(window).ajaxStart(function(){SGE.Inst.spinner.show()});$(window).ajaxStop(function(){SGE.Inst.spinner.hide()})};
SGE.parseMetaXml=function(a){trace("function parseMetaXml");a=$(a).find("main");SGE.mydata={};SGE.mydata.httpURL=a.attr("httpURL");SGE.mydata.cdnURL=a.attr("cdnURL");SGE.mydata.uploadURL=a.attr("uploadURL");SGE.mydata.summaryURL=a.attr("summaryURL");SGE.mydata.subject=-1<SGE.mydata.httpURL.indexOf("jr_kuk_")?"kuk":-1<SGE.mydata.httpURL.indexOf("jr_suh_")?"suh":-1<SGE.mydata.httpURL.indexOf("jr_ton_")?"ton":-1<SGE.mydata.httpURL.indexOf("jr_sah_")?"sah":-1<SGE.mydata.httpURL.indexOf("jr_kwa_")?"kwa":
null;var b=SGE.mydata.httpURL.split("/");SGE.mydata.studyFolder=b.pop();var d=SGE.mydata.studyFolder.split("_");d.splice(4);SGE.mydata.studyCode=d.join("_");b.pop();b=SGE.mydata.studyCode.split("_");SGE.mydata.grade=b[2].charAt(0);SGE.mydata.gradeForm=SGE.getGradeForm(SGE.mydata.grade);SGE.mydata.term=b[2].charAt(2);SGE.mydata.chapter=parseInt(b[3]).toString();SGE.mydata.currentHead=0;SGE.mydata.title=a.find("intro").attr("title");SGE.mydata.unit=a.find("intro").attr("unit");SGE.mydata.page=a.find("content").attr("title").split("|")[1];
trace("SGE.mydata == ",SGE.mydata);SGE.onCompleteParseMetaXml()};SGE.getGradeForm=function(a){return 1==a%2?a+""+(a+1):a-1+""+a};SGE.onCompleteParseMetaXml=function(){trace("SGE.onCompleteParseMetaXml");SGE.loadStyle(SGE.mydata.subject);SGE.Event.trigger(SGE.Event.Const.StartLoadSkin,SGE.Const.SKININTRO)};SGE.loadStyle=function(a){a="css/"+a+"/style.css";document.createStyleSheet?document.createStyleSheet(a):$('<link rel="stylesheet" type="text/css" href="'+a+'" />').appendTo("head")};
SGE.Var.currentSkinStr=null;SGE.Var.nextSkinStr=null;
SGE.loadSkin=function(a,b,d){trace("SGE.loadSkin");SGE.Var.nextSkinStr=a;SGE.Var.currentSkinStr&&"study"!=SGE.Var.currentSkinStr&&SGE.removeCurrentSkin();a="skins/"+SGE.mydata.subject+"/skin_"+a+".html  "+b;console.log("skinUrl="+a);$(d).load(a,function(a,b,c){trace("onComplete skin load");console.timeStamp("onComplete skin loads");$(this).waitForImages(function(){trace("\uc624 \ub85c\ub4dc\uc644\ub8cc\ub124");console.timeStamp("onComplete waitForImages");SGE.onCompleteLoadSkin(this)})})};
SGE.removeCurrentSkin=function(){$("#"+SGE.Var.currentSkin+"css").remove()};SGE.onCompleteLoadSkin=function(a){trace("SGE.onCompleteLoadSkin");SGE.Var.currentSkinStr=SGE.Var.nextSkinStr;SGE.getSkinClassInstance(SGE.Var.currentSkinStr).setStage(a)};
